---
title: "CodeBook"
author: "bbynum"
date: "July 17, 2016"
output: html_document
---

This Code Book describes work on the Getting and Cleaning Data Course Project.
The full description of the data used is found at

[http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones](http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones).
The data for the project is found at 
[https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip](https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip).

### Loading packages and download files
We begin by loading needed packages and downloading the datafile.


### Read needed files
Only a subset of the files will be used in this project and they are read here.

- features: Lists all the variable names.
- activity_labels: Links class labels with activity names.
- X_train: The training data set.
- y_train: The labels identifying the activity for the training data.
- subject_train: The labels identifying the subjects for the training data.
- X_test: The test data set.
- y_test: The labels identifying the activity for the test data.
- subject_test: The labels identifying the subjects for the test data.


###Combine training and test data sets
We combine the training and test data sets.

- X_data: Combined training and test data.
- y_data: Combined activity labels for training and test data.
- subject_data: Combined subject labels for training and test data.

###Select mean and standard deviation variables
Only variables where means or standard deviations are selected. The variable `index` identifies those including either `mean` or `std` in their name. This selection `X_data_selection` is then combined with the `Subject` and `Activity` variables.

- index: Elements of `features` variable name file including mean or std.
- X_data_selection: Combined training and test data for mean and standard deviation variables.

###Merge Data Sets
We merge the `Subject`, `Activity`, and `X_data_selection`.

- data_selection: Combined subject, activity, and mean and standard deviation variables.

###Tidy variable names
The variable names are tidied replacing abbreviations by complete descriptive names and removing unneeded parentheses.

```{r, eval=FALSE}
variable_names <- features[index,2]
variable_names <- gsub("^t", "Time", variable_names)
variable_names <- gsub("^f", "Frequency", variable_names)
variable_names <- gsub("\\(\\)", "", variable_names)
variable_names <- gsub("Acc", "Accelerometer", variable_names)
variable_names <- gsub("Gyro", "Gyroscope", variable_names)
variable_names <- gsub("Mag", "Magnitude", variable_names)
variable_names <- gsub("BodyBody", "Body", variable_names)
variable_names <- gsub("mean", "Mean", variable_names)
variable_names <- gsub("std", "SD", variable_names)
names(data_selection) <- c("Subject", "Activity", as.character(variable_names))
```

###Recode activity variable
The `Activity` variable is recoded using the lowercase version of the descriptive names found in the `activity_labels` file.

###Finalize First Tidy DataSet
The First Tidy Dataset `data_selection` is finalized by ordering the data by `Subject` and `Activity`.

###Generate Second Tidy DataSet 
The Second Tidy DataSet is generated by computing the means of each variable for each `Subject` and `Activity`.

