---
title: "README"
author: "bbynum"
date: "July 17, 2016"
output: html_document
---

The block quote below is from the original information on the dataset found at [http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones#](http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones#):


>==================================================================
>Human Activity Recognition Using Smartphones Dataset
Version 1.0
>==================================================================
>Jorge L. Reyes-Ortiz, Davide Anguita, Alessandro Ghio, Luca Oneto.
>Smartlab - Non Linear Complex Systems Laboratory
>DITEN - Universit‡ degli Studi di Genova.
>Via Opera Pia 11A, I-16145, Genoa, Italy.
>activityrecognition@smartlab.ws
>www.smartlab.ws
>==================================================================

>Data Set Information:
>
>The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data. 

>The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain. See 'features_info.txt' for more details. 


>- Triaxial acceleration from the accelerometer (total acceleration) and the estimated body acceleration.
- Triaxial Angular velocity from the gyroscope. 
- A 561-feature vector with time and frequency domain variables. 
- Its activity label. 
- An identifier of the subject who carried out the experiment.

###The data files 
The above data files were downloaded and our dataset includes the following files:

- features: Lists all the variable names.
- activity_labels: Links class labels with activity names.
- X_train: The training data set.
- y_train: The labels identifying the activity for the training data.
- subject_train: The labels identifying the subjects for the training data.
- X_test: The test data set.
- y_test: The labels identifying the activity for the test data.
- subject_test: The labels identifying the subjects for the test data.

We combine the training and test data sets.

- X_data: Combined training and test data.
- y_data: Combined activity labels for training and test data.
- subject_data: Combined subject labels for training and test data.

We selected mean and standard deviation variables.

- index: Elements of `features` variable name file including mean or std.
- X_data_selection: Combined training and test data for mean and standard deviation variables.

We merge the `Subject`, `Activity`, and `X_data_selection`.

- data_selection: Combined subject, activity, and mean and standard deviation variables.

Tidy variable names were created.

The `Activity` variable was recoded.

The First Tidy Dataset `data_selection` is finalized by ordering the data by `Subject` and `Activity`.

The Second Tidy DataSet is generated by computing the means of each variable for each `Subject` and `Activity`.
